# Generated by Django 5.2.6 on 2025-09-15 17:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Admin Staff', 'Admin Staff'), ('Visitor', 'Visitor'), ('Janitorial Staff', 'Janitorial Staff'), ('Utility Worker', 'Utility Worker'), ('IT Support', 'IT Support'), ('Security Guard', 'Security Guard'), ('Maintenance Officer', 'Maintenance Officer'), ('Registrar', 'Registrar'), ('HR', 'HR'), ('University Admin', 'University Admin')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('requires_admin_approval', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('User Created', 'User Created'), ('Role Assigned', 'Role Assigned'), ('Invite Created', 'Invite Created'), ('Invite Approved', 'Invite Approved'), ('Invite Rejected', 'Invite Rejected')], max_length=50)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_invite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invite')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=100)),
                ('floor_number', models.CharField(max_length=50)),
                ('room_identifier', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('building_name', 'floor_number', 'room_identifier')},
            },
        ),
        migrations.CreateModel(
            name='GuestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_contact', models.CharField(max_length=50)),
                ('tracking_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Structural', 'Structural'), ('HVAC', 'HVAC'), ('Technology', 'Technology'), ('Equipment', 'Equipment'), ('Disturbance', 'Disturbance'), ('Security', 'Security'), ('Parking', 'Parking')], max_length=50)),
                ('urgency', models.CharField(choices=[('Standard', 'Standard'), ('Urgent', 'Urgent')], default='Standard', max_length=50)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Needs Assistance', 'Needs Assistance'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Created', max_length=20)),
                ('escalation_level', models.CharField(choices=[('None', 'None'), ('Secondary', 'Secondary'), ('Admin', 'Admin')], default='None', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Structural', 'Structural'), ('HVAC', 'HVAC'), ('Technology', 'Technology'), ('Equipment', 'Equipment'), ('Disturbance', 'Disturbance'), ('Security', 'Security'), ('Parking', 'Parking')], max_length=50)),
                ('urgency', models.CharField(choices=[('Standard', 'Standard'), ('Urgent', 'Urgent')], default='Standard', max_length=50)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Needs Assistance', 'Needs Assistance'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Reopened', 'Reopened')], default='Created', max_length=20)),
                ('escalation_level', models.CharField(choices=[('None', 'None'), ('Secondary', 'Secondary'), ('Admin', 'Admin')], default='None', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_tickets', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.location')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('guest_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.guestreport')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Created', 'Created'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Needs Assistance', 'Needs Assistance'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Reopened', 'Reopened'), ('Escalated', 'Escalated')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('guest_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.guestreport')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='ticket_images/')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('guest_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.guestreport')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.ticket')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_image', models.ImageField(upload_to='resolutions/')),
                ('resolution_note', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('guest_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='core.guestreport')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='core.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Admin Staff', 'Admin Staff'), ('Visitor', 'Visitor'), ('Janitorial Staff', 'Janitorial Staff'), ('Utility Worker', 'Utility Worker'), ('IT Support', 'IT Support'), ('Security Guard', 'Security Guard'), ('Maintenance Officer', 'Maintenance Officer'), ('Registrar', 'Registrar'), ('HR', 'HR'), ('University Admin', 'University Admin')], max_length=50)),
                ('can_report', models.BooleanField(default=False)),
                ('can_fix', models.BooleanField(default=False)),
                ('can_assign', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_domain', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
