# Generated by Django 5.2.6 on 2025-09-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guest_reports/'),
        ),
    ]
