# Generated by Django 5.2.6 on 2025-09-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='created_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
