# Generated by Django 5.2.6 on 2025-10-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate_roles_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('User Created', 'User Created'), ('User Profile Created', 'User Profile Created'), ('Role Assigned', 'Role Assigned'), ('OTP Verified', 'OTP Verified'), ('OTP Resent', 'OTP Resent'), ('Invite Created', 'Invite Created'), ('Invite Accepted', 'Invite Accepted'), ('Invite Approved', 'Invite Approved'), ('Invite Rejected', 'Invite Rejected'), ('Password Reset Requested', 'Password Reset Requested'), ('Password Reset Confirmed', 'Password Reset Confirmed'), ('Login', 'Login'), ('Logout', 'Logout'), ('Login Failed', 'Login Failed'), ('Token Refreshed', 'Token Refreshed'), ('Ticket Created', 'Ticket Created'), ('Ticket Updated', 'Ticket Updated'), ('Ticket Assigned', 'Ticket Assigned'), ('Ticket Unassigned', 'Ticket Unassigned'), ('Ticket Accepted', 'Ticket Accepted'), ('Ticket Resolved', 'Ticket Resolved'), ('Ticket Closed', 'Ticket Closed'), ('Ticket Reopened', 'Ticket Reopened'), ('Ticket Cancelled', 'Ticket Cancelled'), ('Ticket Escalated', 'Ticket Escalated')], db_index=True, max_length=50),
        ),
    ]
