# Generated by Django 5.2.6 on 2025-09-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentprofile_created_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='created_by_admin',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
